// Code generated by MockGen. DO NOT EDIT.
// Source: ./categories_repository.go

// Package mrepositories is a generated GoMock package.
package mrepositories

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockICategoriesRepository is a mock of ICategoriesRepository interface.
type MockICategoriesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICategoriesRepositoryMockRecorder
}

// MockICategoriesRepositoryMockRecorder is the mock recorder for MockICategoriesRepository.
type MockICategoriesRepositoryMockRecorder struct {
	mock *MockICategoriesRepository
}

// NewMockICategoriesRepository creates a new mock instance.
func NewMockICategoriesRepository(ctrl *gomock.Controller) *MockICategoriesRepository {
	mock := &MockICategoriesRepository{ctrl: ctrl}
	mock.recorder = &MockICategoriesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategoriesRepository) EXPECT() *MockICategoriesRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockICategoriesRepository) FindAll(ctx context.Context) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockICategoriesRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockICategoriesRepository)(nil).FindAll), ctx)
}

// FindBy mocks base method.
func (m *MockICategoriesRepository) FindBy(ctx context.Context, request models.ParamsCategorySearch) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBy", ctx, request)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBy indicates an expected call of FindBy.
func (mr *MockICategoriesRepositoryMockRecorder) FindBy(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBy", reflect.TypeOf((*MockICategoriesRepository)(nil).FindBy), ctx, request)
}

// FirstBy mocks base method.
func (m *MockICategoriesRepository) FirstBy(ctx context.Context, request models.ParamsCategorySearch) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstBy", ctx, request)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstBy indicates an expected call of FirstBy.
func (mr *MockICategoriesRepositoryMockRecorder) FirstBy(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstBy", reflect.TypeOf((*MockICategoriesRepository)(nil).FirstBy), ctx, request)
}

// Upsert mocks base method.
func (m *MockICategoriesRepository) Upsert(ctx context.Context, request models.Category) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, request)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockICategoriesRepositoryMockRecorder) Upsert(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockICategoriesRepository)(nil).Upsert), ctx, request)
}
