// Code generated by MockGen. DO NOT EDIT.
// Source: ./skills_repository.go

// Package mrepositories is a generated GoMock package.
package mrepositories

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockISkillsRepository is a mock of ISkillsRepository interface.
type MockISkillsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISkillsRepositoryMockRecorder
}

// MockISkillsRepositoryMockRecorder is the mock recorder for MockISkillsRepository.
type MockISkillsRepositoryMockRecorder struct {
	mock *MockISkillsRepository
}

// NewMockISkillsRepository creates a new mock instance.
func NewMockISkillsRepository(ctrl *gomock.Controller) *MockISkillsRepository {
	mock := &MockISkillsRepository{ctrl: ctrl}
	mock.recorder = &MockISkillsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillsRepository) EXPECT() *MockISkillsRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockISkillsRepository) FindAll(ctx context.Context) ([]models.SkillsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.SkillsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockISkillsRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockISkillsRepository)(nil).FindAll), ctx)
}

// FindBy mocks base method.
func (m *MockISkillsRepository) FindBy(ctx context.Context, request models.ParamsSkillsSearch) ([]models.SkillsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBy", ctx, request)
	ret0, _ := ret[0].([]models.SkillsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBy indicates an expected call of FindBy.
func (mr *MockISkillsRepositoryMockRecorder) FindBy(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBy", reflect.TypeOf((*MockISkillsRepository)(nil).FindBy), ctx, request)
}
