// Code generated by MockGen. DO NOT EDIT.
// Source: ./skills_categories_repository.go

// Package mrepositories is a generated GoMock package.
package mrepositories

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockISkillsCategoriesRepository is a mock of ISkillsCategoriesRepository interface.
type MockISkillsCategoriesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISkillsCategoriesRepositoryMockRecorder
}

// MockISkillsCategoriesRepositoryMockRecorder is the mock recorder for MockISkillsCategoriesRepository.
type MockISkillsCategoriesRepositoryMockRecorder struct {
	mock *MockISkillsCategoriesRepository
}

// NewMockISkillsCategoriesRepository creates a new mock instance.
func NewMockISkillsCategoriesRepository(ctrl *gomock.Controller) *MockISkillsCategoriesRepository {
	mock := &MockISkillsCategoriesRepository{ctrl: ctrl}
	mock.recorder = &MockISkillsCategoriesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillsCategoriesRepository) EXPECT() *MockISkillsCategoriesRepositoryMockRecorder {
	return m.recorder
}

// FirstBy mocks base method.
func (m *MockISkillsCategoriesRepository) FirstBy(ctx context.Context, request models.ParamsSkillsCategorySearch) (models.SkillCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstBy", ctx, request)
	ret0, _ := ret[0].(models.SkillCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstBy indicates an expected call of FirstBy.
func (mr *MockISkillsCategoriesRepositoryMockRecorder) FirstBy(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstBy", reflect.TypeOf((*MockISkillsCategoriesRepository)(nil).FirstBy), ctx, request)
}

// Upsert mocks base method.
func (m *MockISkillsCategoriesRepository) Upsert(ctx context.Context, request models.SkillCategory) (models.SkillCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, request)
	ret0, _ := ret[0].(models.SkillCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockISkillsCategoriesRepositoryMockRecorder) Upsert(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockISkillsCategoriesRepository)(nil).Upsert), ctx, request)
}
