// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"taska-core-me-go/cmd/api/app/providers"
	"taska-core-me-go/cmd/api/clients/rusty"
	"taska-core-me-go/cmd/api/controllers"
	"taska-core-me-go/cmd/api/repositories"
	"taska-core-me-go/cmd/api/services"
	"taska-core-me-go/cmd/api/validator"
)

// Injectors from app.go:

// 🔹 Start app
func Start() (*echo.Echo, error) {
	db, err := providers.DatabaseConnectionPostgres()
	if err != nil {
		return nil, err
	}
	skillsRepository := providers.SkillsRepository(db)
	skillsServices := providers.SkillsServices(skillsRepository)
	validator := providers.Validator()
	skillsController := providers.SkillsController(skillsServices, validator)
	taskerServices := providers.TaskerServices(skillsRepository)
	taskerController := providers.TaskerController(taskerServices, validator)
	echoEcho := providers.ProviderRouter(skillsController, taskerController)
	return echoEcho, nil
}

// app.go:

// 🔹 Database
var DatabaseSet = wire.NewSet(providers.DatabaseConnectionPostgres)

// 🔹 Clients
var ClientSet = wire.NewSet(providers.GetRustyClient, wire.Bind(new(rusty.IRustyClient), new(*rusty.RustyClient)))

// 🔹 Controllers
var ControllerRouterSet = wire.NewSet(providers.SkillsController, wire.Bind(new(controllers.ISkillsController), new(*controllers.SkillsController)), providers.TaskerController, wire.Bind(new(controllers.ITaskerController), new(*controllers.TaskerController)))

// 🔹 Services
var ServicesRouterSet = wire.NewSet(providers.JwtService, wire.Bind(new(services.IJWTServices), new(*services.JwtServices)), providers.SkillsServices, wire.Bind(new(services.ISkillsServices), new(*services.SkillsServices)), providers.TaskerServices, wire.Bind(new(services.ITaskerServices), new(*services.TaskerServices)))

// 🔹 Repositories
var RepositoryRouterSet = wire.NewSet(providers.RolesTokenRepository, wire.Bind(new(repositories.IRolesRepository), new(*repositories.RolesRepository)), providers.BlacklistedTokenRepository, wire.Bind(new(repositories.IBlacklistedTokenRepository), new(*repositories.BlacklistedTokenRepository)), providers.SkillsRepository, wire.Bind(new(repositories.ISkillsRepository), new(*repositories.SkillsRepository)))

// 🔹 Validators
var ValidatorRouterSet = wire.NewSet(providers.Validator, wire.Bind(new(validator.IValidator), new(*validator.Validator)))

// 🔹 Router
var RouterSet = wire.NewSet(
	ControllerRouterSet,
	ServicesRouterSet,
	RepositoryRouterSet,

	ValidatorRouterSet, providers.ProviderRouter,
)
