// Code generated by MockGen. DO NOT EDIT.
// Source: ./categories_services.go

// Package mservices is a generated GoMock package.
package mservices

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockICategoriesServices is a mock of ICategoriesServices interface.
type MockICategoriesServices struct {
	ctrl     *gomock.Controller
	recorder *MockICategoriesServicesMockRecorder
}

// MockICategoriesServicesMockRecorder is the mock recorder for MockICategoriesServices.
type MockICategoriesServicesMockRecorder struct {
	mock *MockICategoriesServices
}

// NewMockICategoriesServices creates a new mock instance.
func NewMockICategoriesServices(ctrl *gomock.Controller) *MockICategoriesServices {
	mock := &MockICategoriesServices{ctrl: ctrl}
	mock.recorder = &MockICategoriesServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategoriesServices) EXPECT() *MockICategoriesServicesMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockICategoriesServices) List(ctx context.Context) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockICategoriesServicesMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockICategoriesServices)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockICategoriesServices) Save(ctx context.Context, request models.ParamsCategorySave) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockICategoriesServicesMockRecorder) Save(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockICategoriesServices)(nil).Save), ctx, request)
}

// Search mocks base method.
func (m *MockICategoriesServices) Search(ctx context.Context, request models.ParamsCategorySearch) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, request)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockICategoriesServicesMockRecorder) Search(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockICategoriesServices)(nil).Search), ctx, request)
}

// Update mocks base method.
func (m *MockICategoriesServices) Update(ctx context.Context, id int64, request models.ParamsCategorySave) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, request)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockICategoriesServicesMockRecorder) Update(ctx, id, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICategoriesServices)(nil).Update), ctx, id, request)
}
