// Code generated by MockGen. DO NOT EDIT.
// Source: ./skills_services.go

// Package mservices is a generated GoMock package.
package mservices

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockISkillsServices is a mock of ISkillsServices interface.
type MockISkillsServices struct {
	ctrl     *gomock.Controller
	recorder *MockISkillsServicesMockRecorder
}

// MockISkillsServicesMockRecorder is the mock recorder for MockISkillsServices.
type MockISkillsServicesMockRecorder struct {
	mock *MockISkillsServices
}

// NewMockISkillsServices creates a new mock instance.
func NewMockISkillsServices(ctrl *gomock.Controller) *MockISkillsServices {
	mock := &MockISkillsServices{ctrl: ctrl}
	mock.recorder = &MockISkillsServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillsServices) EXPECT() *MockISkillsServicesMockRecorder {
	return m.recorder
}

// SkillsList mocks base method.
func (m *MockISkillsServices) SkillsList(ctx context.Context) ([]models.Skills, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkillsList", ctx)
	ret0, _ := ret[0].([]models.Skills)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SkillsList indicates an expected call of SkillsList.
func (mr *MockISkillsServicesMockRecorder) SkillsList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkillsList", reflect.TypeOf((*MockISkillsServices)(nil).SkillsList), ctx)
}

// SkillsSearch mocks base method.
func (m *MockISkillsServices) SkillsSearch(ctx context.Context, request models.ParamsSkillsSearch) ([]models.Skills, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkillsSearch", ctx, request)
	ret0, _ := ret[0].([]models.Skills)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SkillsSearch indicates an expected call of SkillsSearch.
func (mr *MockISkillsServicesMockRecorder) SkillsSearch(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkillsSearch", reflect.TypeOf((*MockISkillsServices)(nil).SkillsSearch), ctx, request)
}
