// Code generated by MockGen. DO NOT EDIT.
// Source: ./skills_categories_services.go

// Package mservices is a generated GoMock package.
package mservices

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockISkillsCategoriesServices is a mock of ISkillsCategoriesServices interface.
type MockISkillsCategoriesServices struct {
	ctrl     *gomock.Controller
	recorder *MockISkillsCategoriesServicesMockRecorder
}

// MockISkillsCategoriesServicesMockRecorder is the mock recorder for MockISkillsCategoriesServices.
type MockISkillsCategoriesServicesMockRecorder struct {
	mock *MockISkillsCategoriesServices
}

// NewMockISkillsCategoriesServices creates a new mock instance.
func NewMockISkillsCategoriesServices(ctrl *gomock.Controller) *MockISkillsCategoriesServices {
	mock := &MockISkillsCategoriesServices{ctrl: ctrl}
	mock.recorder = &MockISkillsCategoriesServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillsCategoriesServices) EXPECT() *MockISkillsCategoriesServicesMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockISkillsCategoriesServices) Save(ctx context.Context, request models.ParamsSkillsCategorySave) (models.SkillCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(models.SkillCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockISkillsCategoriesServicesMockRecorder) Save(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockISkillsCategoriesServices)(nil).Save), ctx, request)
}

// Update mocks base method.
func (m *MockISkillsCategoriesServices) Update(ctx context.Context, id int64, request models.ParamsSkillsCategorySave) (models.SkillCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, request)
	ret0, _ := ret[0].(models.SkillCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockISkillsCategoriesServicesMockRecorder) Update(ctx, id, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISkillsCategoriesServices)(nil).Update), ctx, id, request)
}
