// Code generated by MockGen. DO NOT EDIT.
// Source: ./skills_services.go

// Package mservices is a generated GoMock package.
package mservices

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockISkillsServices is a mock of ISkillsServices interface.
type MockISkillsServices struct {
	ctrl     *gomock.Controller
	recorder *MockISkillsServicesMockRecorder
}

// MockISkillsServicesMockRecorder is the mock recorder for MockISkillsServices.
type MockISkillsServicesMockRecorder struct {
	mock *MockISkillsServices
}

// NewMockISkillsServices creates a new mock instance.
func NewMockISkillsServices(ctrl *gomock.Controller) *MockISkillsServices {
	mock := &MockISkillsServices{ctrl: ctrl}
	mock.recorder = &MockISkillsServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillsServices) EXPECT() *MockISkillsServicesMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockISkillsServices) List(ctx context.Context) ([]models.Skills, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Skills)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockISkillsServicesMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockISkillsServices)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockISkillsServices) Save(ctx context.Context, request models.ParamsSkillsSave) (models.Skills, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(models.Skills)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockISkillsServicesMockRecorder) Save(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockISkillsServices)(nil).Save), ctx, request)
}

// Search mocks base method.
func (m *MockISkillsServices) Search(ctx context.Context, request models.ParamsSkillsSearch) ([]models.Skills, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, request)
	ret0, _ := ret[0].([]models.Skills)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockISkillsServicesMockRecorder) Search(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockISkillsServices)(nil).Search), ctx, request)
}

// Update mocks base method.
func (m *MockISkillsServices) Update(ctx context.Context, id int64, request models.ParamsSkillsSave) (models.Skills, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, request)
	ret0, _ := ret[0].(models.Skills)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockISkillsServicesMockRecorder) Update(ctx, id, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISkillsServices)(nil).Update), ctx, id, request)
}
