// Code generated by MockGen. DO NOT EDIT.
// Source: ./tasker_services.go

// Package mservices is a generated GoMock package.
package mservices

import (
	context "context"
	reflect "reflect"
	models "taska-core-me-go/cmd/api/models"

	gomock "github.com/golang/mock/gomock"
)

// MockITaskerServices is a mock of ITaskerServices interface.
type MockITaskerServices struct {
	ctrl     *gomock.Controller
	recorder *MockITaskerServicesMockRecorder
}

// MockITaskerServicesMockRecorder is the mock recorder for MockITaskerServices.
type MockITaskerServicesMockRecorder struct {
	mock *MockITaskerServices
}

// NewMockITaskerServices creates a new mock instance.
func NewMockITaskerServices(ctrl *gomock.Controller) *MockITaskerServices {
	mock := &MockITaskerServices{ctrl: ctrl}
	mock.recorder = &MockITaskerServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskerServices) EXPECT() *MockITaskerServicesMockRecorder {
	return m.recorder
}

// GetTasker mocks base method.
func (m *MockITaskerServices) GetTasker(ctx context.Context, request models.ParamsProfile) (models.Tasker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasker", ctx, request)
	ret0, _ := ret[0].(models.Tasker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasker indicates an expected call of GetTasker.
func (mr *MockITaskerServicesMockRecorder) GetTasker(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasker", reflect.TypeOf((*MockITaskerServices)(nil).GetTasker), ctx, request)
}
