// Code generated by MockGen. DO NOT EDIT.
// Source: ./categories_controllers.go

// Package mcontrollers is a generated GoMock package.
package mcontrollers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockICategoriesController is a mock of ICategoriesController interface.
type MockICategoriesController struct {
	ctrl     *gomock.Controller
	recorder *MockICategoriesControllerMockRecorder
}

// MockICategoriesControllerMockRecorder is the mock recorder for MockICategoriesController.
type MockICategoriesControllerMockRecorder struct {
	mock *MockICategoriesController
}

// NewMockICategoriesController creates a new mock instance.
func NewMockICategoriesController(ctrl *gomock.Controller) *MockICategoriesController {
	mock := &MockICategoriesController{ctrl: ctrl}
	mock.recorder = &MockICategoriesControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategoriesController) EXPECT() *MockICategoriesControllerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockICategoriesController) List(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockICategoriesControllerMockRecorder) List(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockICategoriesController)(nil).List), c)
}

// Save mocks base method.
func (m *MockICategoriesController) Save(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockICategoriesControllerMockRecorder) Save(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockICategoriesController)(nil).Save), c)
}

// Search mocks base method.
func (m *MockICategoriesController) Search(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Search indicates an expected call of Search.
func (mr *MockICategoriesControllerMockRecorder) Search(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockICategoriesController)(nil).Search), c)
}

// Update mocks base method.
func (m *MockICategoriesController) Update(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICategoriesControllerMockRecorder) Update(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICategoriesController)(nil).Update), c)
}
