// Code generated by MockGen. DO NOT EDIT.
// Source: ./skills_controllers.go

// Package mcontrollers is a generated GoMock package.
package mcontrollers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockISkillsController is a mock of ISkillsController interface.
type MockISkillsController struct {
	ctrl     *gomock.Controller
	recorder *MockISkillsControllerMockRecorder
}

// MockISkillsControllerMockRecorder is the mock recorder for MockISkillsController.
type MockISkillsControllerMockRecorder struct {
	mock *MockISkillsController
}

// NewMockISkillsController creates a new mock instance.
func NewMockISkillsController(ctrl *gomock.Controller) *MockISkillsController {
	mock := &MockISkillsController{ctrl: ctrl}
	mock.recorder = &MockISkillsControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillsController) EXPECT() *MockISkillsControllerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockISkillsController) List(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockISkillsControllerMockRecorder) List(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockISkillsController)(nil).List), c)
}

// Save mocks base method.
func (m *MockISkillsController) Save(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockISkillsControllerMockRecorder) Save(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockISkillsController)(nil).Save), c)
}

// Search mocks base method.
func (m *MockISkillsController) Search(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Search indicates an expected call of Search.
func (mr *MockISkillsControllerMockRecorder) Search(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockISkillsController)(nil).Search), c)
}

// Update mocks base method.
func (m *MockISkillsController) Update(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockISkillsControllerMockRecorder) Update(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISkillsController)(nil).Update), c)
}
