// Code generated by MockGen. DO NOT EDIT.
// Source: ./skills_controllers.go

// Package mcontrollers is a generated GoMock package.
package mcontrollers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockISkillsController is a mock of ISkillsController interface.
type MockISkillsController struct {
	ctrl     *gomock.Controller
	recorder *MockISkillsControllerMockRecorder
}

// MockISkillsControllerMockRecorder is the mock recorder for MockISkillsController.
type MockISkillsControllerMockRecorder struct {
	mock *MockISkillsController
}

// NewMockISkillsController creates a new mock instance.
func NewMockISkillsController(ctrl *gomock.Controller) *MockISkillsController {
	mock := &MockISkillsController{ctrl: ctrl}
	mock.recorder = &MockISkillsControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillsController) EXPECT() *MockISkillsControllerMockRecorder {
	return m.recorder
}

// SkillsList mocks base method.
func (m *MockISkillsController) SkillsList(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkillsList", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SkillsList indicates an expected call of SkillsList.
func (mr *MockISkillsControllerMockRecorder) SkillsList(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkillsList", reflect.TypeOf((*MockISkillsController)(nil).SkillsList), c)
}

// SkillsProfile mocks base method.
func (m *MockISkillsController) SkillsProfile(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkillsProfile", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SkillsProfile indicates an expected call of SkillsProfile.
func (mr *MockISkillsControllerMockRecorder) SkillsProfile(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkillsProfile", reflect.TypeOf((*MockISkillsController)(nil).SkillsProfile), c)
}

// SkillsSearch mocks base method.
func (m *MockISkillsController) SkillsSearch(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkillsSearch", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SkillsSearch indicates an expected call of SkillsSearch.
func (mr *MockISkillsControllerMockRecorder) SkillsSearch(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkillsSearch", reflect.TypeOf((*MockISkillsController)(nil).SkillsSearch), c)
}
