// Code generated by MockGen. DO NOT EDIT.
// Source: ./tasker_controllers.go

// Package mcontrollers is a generated GoMock package.
package mcontrollers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockITaskerController is a mock of ITaskerController interface.
type MockITaskerController struct {
	ctrl     *gomock.Controller
	recorder *MockITaskerControllerMockRecorder
}

// MockITaskerControllerMockRecorder is the mock recorder for MockITaskerController.
type MockITaskerControllerMockRecorder struct {
	mock *MockITaskerController
}

// NewMockITaskerController creates a new mock instance.
func NewMockITaskerController(ctrl *gomock.Controller) *MockITaskerController {
	mock := &MockITaskerController{ctrl: ctrl}
	mock.recorder = &MockITaskerControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskerController) EXPECT() *MockITaskerControllerMockRecorder {
	return m.recorder
}

// TaskerProfile mocks base method.
func (m *MockITaskerController) TaskerProfile(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskerProfile", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskerProfile indicates an expected call of TaskerProfile.
func (mr *MockITaskerControllerMockRecorder) TaskerProfile(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskerProfile", reflect.TypeOf((*MockITaskerController)(nil).TaskerProfile), c)
}
